stages:
  - build
  - test
  - deploy
build:
  stage: build
  tags:
    - Riskine
  script:
    - echo "building"
test:
  stage: test
  tags:
    - Riskine
  script:
    - echo "testing"
deploy:
  stage: deploy
  tags:
    - Riskine
  script:
    - echo "deploying"
