stages:
  - build
  - test
  - deploy
build:
  stage: build
  tags:
    - Riskine
  script:
    - echo "build"
test:
  stage: test
  tags:
    - Riskine
  script:
    - echo "test"
deploy:
  stage: deploy
  tags:
    - Riskine
  script:
    - echo "deploy"