stages:
  - build
  - test
  - deploy
build:
  stage: build
  image: python:3.8-slim-buster
  tags:
    - Riskine
  script:
    - echo "building"
test:
  stage: test
  image: python:3.8-slim-buster
  tags:
    - Riskine
  script:
    - echo "testing"
deploy:
  stage: deploy
  image: python:3.8-slim-buster
  tags:
    - Riskine
  script:
    - echo "deploying"
