version: "3"

networks:
  default:
    driver: "bridge"
  web:


services:
  traefik:
    image: "traefik:latest"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"                                                             # The Web UI (enabled by --api.insecure=true)
    volumes:
      # - ./Traefik/config.yml:/etc/traefik/config.yml               # Set the dynamic configuration for the file provider
      - "./Services/Traefik/traefik.yml:/etc/traefik/traefik.yml"             # Set the static configuration
      - "./Services/Traefik/letsencrypt:/letsencrypt"                                    # Set the location where my ACME certificates are saved to
      - "//var/run/docker.sock:/var/run/docker.sock"                              # Give access to the Windows Docker socket
    labels:
      - "traefik.enable=true"
  
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    volumes:
      - "./Services/GitLab/config:/etc/gitlab"
      - "./Services/GitLab/logs:/var/log/gitlab"
      - "./Services/GitLab/data:/var/opt/gitlab"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.docker.localhost`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    depends_on:
      - "gitlab"
    volumes:
      - "./Services/GitLab/runner/config:/etc/gitlab-runner"
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.gitlab-runner.rule=Host(`runner.docker.localhost`)"

  front-end:
    build: "./Services/Frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-end.rule=Host(`fe.docker.localhost`)"
      - "traefik.http.services.front-end.loadbalancer.server.port=80"

  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  nginx:
    image: "nginx:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.docker.localhost`)"