version: "3.8"

services:

  frontend:
    # Dockerfile exists in root
    build: ./Frontend
    # Map host port to container port
    ports:
      - 5000:3000

  backend:
    build: ./Backend
    # Map host port to container port
    ports:
      - 5001:3001
    environment:
      # RiskineApplication is the application name
      DB_URL: mongodb://database/RiskineApplication

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      # By default Mongo DB stores data in /data/db
      - RiskineApplication:/data/db

# Define the volume before it can be used
volumes:
  RiskineApplication: