version: '3'

networks:
  default:
    driver: 'bridge'

volumes:
  gitLab-config:
  gitLab-logs:
  gitLab-data:
  gitlab-runner-config:

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    # restart: always
    ports:
      - '80:80'
    volumes:
#     persist database using volumes and docker container
      - 'gitLab-config:/etc/gitlab'
      - 'gitLab-logs:/var/log/gitlab'
      - 'gitLab-data:/var/opt/gitlab'
    networks:
      - 'default'

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    depends_on:
      - 'gitlab'
    # restart: always
    volumes:
      - 'gitlab-runner-config:/etc/gitlab-runner'
    networks:
      - 'default'

  front-end:
    build: ./Frontend
    # restart: always
    ports:
      - '3000:3000'