version: "3.8"

services:

  web:
    # Community edition GitLab
    image: "gitlab/gitlab-ce:latest"
    restart: always
#    hostname: "gitlab.michaelthamm.com"
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'https://gitlab.michaelthamm.com'
#        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 8080:80
      - 443:443
      - 8081:22
    volumes:
      - "GitLab-config:/etc/gitlab"
      - "GitLab-logs:/var/log/gitlab"
      - "GitLab-data:/var/opt/gitlab"
    shm_size: '2gb'

  frontend:
    # Dockerfile exists in root
    build: ./Frontend
    # Map host port to container port
    ports:
      - 5000:3000

#  backend:
#    build: ./Backend
#    # Map host port to container port
#    ports:
#      - 5001:3000
#    environment:
#      # RiskineApplication is the application name
#      DB_URL: mongodb://database/RiskineApplication

#  database:
#    image: mongo:4.0-xenial
#    ports:
#      - 27017:27017
#    volumes:
#      # By default Mongo DB stores data in /data/db
#      - RiskineApplication:/data/db

#  traefik:
#    image: "traefik:v2.5"
#    container_name: "traefik"
#    ports:
#      - "80:80"
#      - "443:443"
#      # (Optional) Expose Dashboard
#      - "8080:8080"  # Don't do this in production!
#    volumes:
#      - /etc/traefik:/etc/traefik
#      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  GitLab-config:
  GitLab-logs:
  GitLab-data:
  traefik-ssl-certs:
    driver: local