version: "3.8"

services:

  web:
    # Community edition GitLab
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "gitlab.michaelthamm.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.michaelthamm.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 8080:80
      - 443:443
      - 8081:22
    volumes:
      - "config:/etc/gitlab"
      - "logs:/var/log/gitlab"
      - "data:/var/opt/gitlab"
    shm_size: '2gb'

frontend:
  # Dockerfile exists in root
  build: ./Frontend
  # Map host port to container port
  ports:
    - 5000:3000

#  traefik:
#    image: "traefik:v2.5"
#    container_name: "traefik"
#    ports:
#      - "80:80"
#      - "443:443"
#      # (Optional) Expose Dashboard
#      - "8080:8080"  # Don't do this in production!
#    volumes:
#      - /etc/traefik:/etc/traefik
#      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  config:
  logs:
  data:
  # traefik-ssl-certs:
  #   driver: local
