# syntax=docker/dockerfile:1

FROM gitlab/gitlab-ce:latest

#RUN clear

#RUN apt-get update && apt-get -y install sudo
#RUN sudo apt-get update
#RUN sudo apt-get install ca-certificates curl gnupg lsb-release
#RUN Y
#RUN sudo mkdir -p /etc/apt/keyrings
#RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
#RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
#RUN sudo apt-get update
#RUN sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
#RUN Y
